import type { Metadata } from "next";
import "./globals.css";
import BottomTab from "@/components/layout/BottomTab";
import { TRPCProvider } from "./providers";


export const metadata: Metadata = {
  title: "Seoul Comix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased`}
      >
        <TRPCProvider>
          {children}
        </TRPCProvider>


        <BottomTab />
      </body>
    </html>
  );
}
